name: "GKE"

on:
  workflow_run:
    workflows: ["TFLint Checks"]
    types:
      - completed

permissions:
  id-token: write
  contents: read
  pull-requests: write
env:
  TF_LOG: INFO

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        version: '>= 363.0.0'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: fetch do cluster auth
      run: gcloud container clusters get-credentials meu-cluster-autopilot --region southamerica-east1
    
    - name: kubectl get namespaces
      run: kubectl get namespaces